universe:
  equities:
  - SPY
  - QQQ
  - EFA
  - EEM
  - IWM
  - VNQ
  - XLK
  - XLF
  - XLE
  - XLV
  - XLB
  - XLY
  - XLP
  - IEF
  - TLT
  - LQD
  - HYG
  - SHY
  - TIP
  - BNDX
  - GLD
  - SLV
  - DBC
  - USO
  - BTC-USD
  - ETH-USD
constraints:
  max_weight: 0.3
  long_only: true
  cash_buffer: 0.0
