name: daily-refresh
on:
  schedule:
    - cron: "15 6 * * 1-5"   # 06:15 UTC on weekdays
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - name: Run daily pipeline
        run: python scripts/run_daily.py --config configs/default.yaml
      - name: Commit artifacts
        run: |
          git config user.name "bot"
          git config user.email "bot@users.noreply.github.com"
          git add -A
          git commit -m "daily refresh" || echo "no changes"
          git push