name: daily-refresh
on:
  schedule:
    - cron: "15 6 * * 1-5"  # Runs at 6:15 AM UTC Monday-Friday
  workflow_dispatch:  # Allows manual triggering
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
      ALPHA_VANTAGE_KEY: ${{ secrets.ALPHA_VANTAGE_KEY }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install lightgbm
      
      - name: Run pipeline
        run: |
          source .venv/bin/activate
          python -m pipeline.fetch_market    --config configs/default.yaml
          python -m pipeline.build_features  --config configs/default.yaml
          python -m pipeline.optimize        --config configs/default.yaml
          python -m pipeline.walkforward     --config configs/default.yaml
          python -m pipeline.stress          --config configs/default.yaml
          python -m pipeline.backtest        --config configs/default.yaml
          python -m pipeline.trades          --config configs/default.yaml --notional 100000
          python -m pipeline.attribution     --config configs/default.yaml
      
      - name: Commit results
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/processed/*.csv
          git add reports/*.png || echo "No reports to add"
          git commit -m "CI: daily refresh [skip ci]" || echo "No changes to commit"
          git push